# Generated by Django 2.0.3 on 2018-03-26 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_number', models.IntegerField(default=0)),
                ('match_number', models.CharField(max_length=200)),
                ('auton', models.CharField(choices=[('None', 'None'), ('Baseline', 'Baseline'), ('CenterSwitch', 'Center Switch'), ('SideSwitch', 'Side Switch'), ('Scale', 'Scale')], default='None', max_length=30)),
                ('auto_cubes', models.IntegerField(default=0)),
                ('auto_notes', models.CharField(max_length=200)),
                ('own_switch_cubes', models.IntegerField(default=0)),
                ('other_switch_cubes', models.IntegerField(default=0)),
                ('scale_cubes', models.IntegerField(default=0)),
                ('vault_cubes', models.IntegerField(default=0)),
                ('tele_notes', models.CharField(max_length=200)),
                ('can_climb', models.BooleanField(default=False)),
                ('buddy_climb', models.BooleanField(default=False)),
                ('robot_speed', models.IntegerField(default=0)),
                ('robot_cube_intake', models.IntegerField(default=0)),
                ('robot_cube_holding', models.IntegerField(default=0)),
                ('robot_cube_placing', models.IntegerField(default=0)),
                ('other_notes', models.CharField(max_length=200)),
                ('scouter_name', models.CharField(max_length=200)),
            ],
        ),
    ]
