# Generated by Django 2.0.3 on 2018-03-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='auto_notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='other_notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='scouter_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='tele_notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
